name: goreleaser

on:
    pull_request:
    push:
      branches:
        - main

jobs:
  artifact-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: |
            go get github.com/c-bata/go-prompt
            go get google.golang.org/grpc

      - name: Build darwin
        if: matrix.os == 'macos-latest'
        run: |
          make buildcli-mac
           
      - name: Build linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          make buildcli-lin 
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gk-client-${{ matrix.os }}-amd64
          path: build/gk-client-${{ matrix.os }}-amd64
